# Generated by Django 5.0.6 on 2024-05-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_capturedimage_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='predicted_skin_type',
            field=models.CharField(blank=True, default='acne', max_length=100, null=True),
        ),
    ]
