# Generated by Django 5.0.6 on 2024-05-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_predicted_skin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
